import { ethers } from "hardhat";
import fs from "fs";
import path from "path";

async function main() {
  console.log("🚀 Deploying contracts and connecting to frontend...\n");

  // Get the deployer account
  const [deployer] = await ethers.getSigners();
  console.log("📝 Deploying with account:", deployer.address);

  // Get account balance
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Account balance:", ethers.formatEther(balance), "ETH\n");

  // Deploy MockStakingToken
  console.log("📦 Deploying MockStakingToken...");
  const MockStakingToken = await ethers.getContractFactory("MockStakingToken");
  const stakingToken = await MockStakingToken.deploy();
  await stakingToken.waitForDeployment();
  const tokenAddress = await stakingToken.getAddress();
  console.log("✅ MockStakingToken deployed to:", tokenAddress);

  // Deploy VotingSystem
  console.log("📦 Deploying VotingSystem...");
  const VotingSystem = await ethers.getContractFactory("VotingSystem");
  const votingSystem = await VotingSystem.deploy(tokenAddress);
  await votingSystem.waitForDeployment();
  const contractAddress = await votingSystem.getAddress();
  console.log("✅ VotingSystem deployed to:", contractAddress);

  // Add deployer as member
  console.log("\n🔐 Setting up initial member...");
  const tx = await votingSystem.addMember(deployer.address);
  await tx.wait();
  console.log("✅ Deployer added as member");

  // Network info
  const network = await ethers.provider.getNetwork();
  const timestamp = new Date().toISOString();

  // Save deployment info
  const deploymentInfo = {
    network: "localhost",
    chainId: network.chainId.toString(),
    votingSystem: contractAddress,
    stakingToken: tokenAddress,
    deployer: deployer.address,
    timestamp: timestamp,
  };

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const deploymentFile = path.join(deploymentsDir, "latest-localhost.json");
  fs.writeFileSync(deploymentFile, JSON.stringify(deploymentInfo, null, 2));
  console.log("\n💾 Deployment info saved to:", deploymentFile);

  // ============================================
  // FRONTEND INTEGRATION
  // ============================================

  console.log("\n🔗 Connecting to frontend...");

  // Frontend path (relative to contract project)
  const frontendPath = path.join(__dirname, "..", "..", "voting-dapp-keystone");

  // Check if frontend exists
  if (!fs.existsSync(frontendPath)) {
    console.log("⚠️  Frontend project not found at:", frontendPath);
    console.log("❌ Skipping frontend integration");
    return;
  }

  console.log("📁 Frontend project found at:", frontendPath);

  // 1. Create contracts directory in frontend
  const frontendContractsDir = path.join(frontendPath, "src", "contracts");
  if (!fs.existsSync(frontendContractsDir)) {
    fs.mkdirSync(frontendContractsDir, { recursive: true });
    console.log("✅ Created contracts directory in frontend");
  }

  // 2. Copy ABIs
  console.log("\n📋 Copying contract ABIs...");

  const votingSystemArtifact = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "VotingSystem.sol",
    "VotingSystem.json"
  );

  const stakingTokenArtifact = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "MockStakingToken.sol",
    "MockStakingToken.json"
  );

  // Copy VotingSystem ABI
  if (fs.existsSync(votingSystemArtifact)) {
    fs.copyFileSync(
      votingSystemArtifact,
      path.join(frontendContractsDir, "VotingSystem.json")
    );
    console.log("✅ Copied VotingSystem.json");
  }

  // Copy MockStakingToken ABI
  if (fs.existsSync(stakingTokenArtifact)) {
    fs.copyFileSync(
      stakingTokenArtifact,
      path.join(frontendContractsDir, "MockStakingToken.json")
    );
    console.log("✅ Copied MockStakingToken.json");
  }

  // 3. Update .env.local
  console.log("\n⚙️  Updating frontend .env.local...");

  const envPath = path.join(frontendPath, ".env.local");
  const envContent = `# Auto-generated by deploy-and-connect.ts
# Last updated: ${timestamp}

# Contract Addresses (Localhost)
VITE_VOTING_SYSTEM_ADDRESS=${contractAddress}
VITE_STAKING_TOKEN_ADDRESS=${tokenAddress}

# Network Configuration
VITE_CHAIN_ID=1337
VITE_RPC_URL=http://127.0.0.1:8545

# Deployer Account (for reference)
# VITE_DEPLOYER_ADDRESS=${deployer.address}
`;

  fs.writeFileSync(envPath, envContent);
  console.log("✅ Updated .env.local with contract addresses");

  // 4. Create a contract config helper (optional)
  const configContent = `// Auto-generated by deploy-and-connect.ts
// Last updated: ${timestamp}

export const CONTRACT_ADDRESSES = {
  votingSystem: "${contractAddress}" as \`0x\${string}\`,
  stakingToken: "${tokenAddress}" as \`0x\${string}\`,
} as const;

export const NETWORK_CONFIG = {
  chainId: 1337,
  rpcUrl: "http://127.0.0.1:8545",
  name: "Hardhat Local",
} as const;

export const DEPLOYER_ADDRESS = "${deployer.address}" as \`0x\${string}\`;
`;

  const configPath = path.join(frontendContractsDir, "addresses.ts");
  fs.writeFileSync(configPath, configContent);
  console.log("✅ Created addresses.ts config file");

  // Summary
  console.log("\n" + "=".repeat(60));
  console.log("🎉 DEPLOYMENT & FRONTEND CONNECTION COMPLETE!");
  console.log("=".repeat(60));
  console.log("\n📋 Contract Addresses:");
  console.log("   VotingSystem:   ", contractAddress);
  console.log("   StakingToken:   ", tokenAddress);
  console.log("\n📁 Frontend Files Updated:");
  console.log("   ✅", path.relative(process.cwd(), envPath));
  console.log("   ✅", path.relative(process.cwd(), path.join(frontendContractsDir, "VotingSystem.json")));
  console.log("   ✅", path.relative(process.cwd(), path.join(frontendContractsDir, "MockStakingToken.json")));
  console.log("   ✅", path.relative(process.cwd(), configPath));
  console.log("\n🚀 Next Steps:");
  console.log("   1. Frontend .env.local is ready");
  console.log("   2. Contract ABIs are in src/contracts/");
  console.log("   3. Start your frontend: cd ../voting-dapp-keystone && npm run dev");
  console.log("\n💡 If you redeploy, just run this command again!");
  console.log("=".repeat(60) + "\n");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Error:", error);
    process.exit(1);
  });
